### ISSUE TITLE
Rebasing on the latest io-uring upstream

### ISSUE THREAD

**Issue by sunfishcode** [jordanisaacs/rustix-uring#6]
I'd like to update rustix-uring to be based on the latest io-uring changes, as it adds important features and fixes.

One way to do that would be to use merge commits and preserve the history of this branch, however I find that approach makes it harder to see how this branch relates to the upstream branch. I'd find it clearer to have rewritten history when we incorporate io-uring changes, so that the repository can just be a series of patches on top of the upstream branch point. To illustrate what this looks like, I've prepared such a branch here:

https://github.com/jordanisaacs/rustix-uring/tree/rebase-on-upstream

I also made a few changes to reduce the size of the diffs with the upstream tree, such as using `use rustix::io_uring as sys;` so that most of the code can keep using the `sys::` name.

The way I envision this would work is, we'd create a tag for the current `main` to keep it accessible, and then replace the current `main` with this `rebase-on-upstream` branch.

Do you have any concerns about this approach?

**Comment by jordanisaacs** [comment]
Ya I like the rebase approach a lot! Makes it much easier to keep it with the upstream. I'm not a stickler for keeping the history of the branch vs. just ensuring that commits have the right author. Especially because this project is sort of a downstream of the original io-uring repo anyway.

**Comment by sunfishcode** [comment]
Sounds good! I've now rebased it.
