### ISSUE TITLE
Unsound issue in BufRingEntry

### ISSUE THREAD

**Issue by CXWorks** [jordanisaacs/rustix-uring#8]
Hi, thanks for your time to read this issue. Our static analysis tool found there might be an unsound issue in your `set_len` implementation of buffer:

https://github.com/jordanisaacs/rustix-uring/blob/8e831472a3d37f6ffccd5145266a176469570964/src/types.rs#L294-L296

Because this can change the logical length of the buffer, which may introduce the uninitialized memory. As a reference, in std library, all the `set_len` method are marked as unsafe:

https://github.com/rust-lang/rust/blob/63a0bdd5622eaf6b9524702f055bb4525acfc9f2/library/alloc/src/vec/mod.rs#L1849-L1853

Thanks again for your time.

**Comment by sunfishcode** [comment]
This code comes from the upstream [io-uring crate](https://github.com/tokio-rs/io-uring/blob/a2fed13cee293ac3cf5bef51c4b0d5fc5a2a5a69/src/types.rs#L294).

It's not clear that it's unsound, as this `set_len` method is for the `BufRingEntry` type, which unlike `Vec::set_len`, does not provide any functions to access the buffer.
